version: '3.8'

services:
  app1:
    build: .
    container_name: app1

  app2:
    build: .
    container_name: app2

  app3:
    build: .
    container_name: app3

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - app1
      - app2
      - app3
